# Tomcat
server:
  port: 14660

# Spring
spring:
  application:
    # 应用名称
    name: aiera-ai
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:aiera-system.yml
      - optional:nacos:${spring.application.name}.yml


#spring:
#  ai:
#    ollama:
#      # 填写模型所在的地址
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:8b
#    vectorstore:
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        databaseName: "default"
#        collectionName: "vector_store"
#        embeddingDimension: 1536
#        indexType: IVF_FLAT
#        metricType: COSINE
#      redis:
#        initialize-schema: true
#        index-name: custom-index
#        prefix: custom-prefix
#        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding