# Compose a postgres database together with the extension pgvector
services:
  pgvector:
    image: docker.m.daocloud.io/pgvector/pgvector:0.7.2-pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=aiera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aiera
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - ./redis_data:/data
    command: "redis-server --bind 0.0.0.0 --appendonly yes --requirepass 123456"
    restart: always