server:
  port: 8100

spring:
  # 数据库配置
  datasource:
    biz-db:
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/aiera?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        keep-alive: true
    vector-db:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5432/aiera
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      druid:
        keep-alive: true
  # ai
#  ai:
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#        dimensions: 1536
#        schema-name: aiera


  # Redis配置
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      jedis:
        pool:
          max-wait: 2000
          time-between-eviction-runs: 1000
      password: 123456


#logging:
#  config: classpath:conf/log4j2-dev.xml