server:
  tomcat:
    uri-encoding: utf-8

project:
  version: @project.version@
  url: @app.url@



spring:
  # 应用名称
  application:
    name: aiera
  # 默认执行的配置文件
  profiles:
    active: dev
  # 国际化配置
  messages:
    basename: i18n.messages
    encoding: UTF-8
    cache-duration: 3600
    fallback-to-system-locale: true
  main:
    allow-bean-definition-overriding: true

    #   Cache设置
    cache:
      type: redis

  # 文件上传相关设置
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    async:
      request-timeout: 3600000

# MybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

#logging:
#  level:
#    dev:
#      ai4j:
#        openai4j: DEBUG

# swagger配置 访问地址http://localhost:8100/swagger-ui/index.html
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
